---
driver:
  name: vagrant

role_name_check: 1

platforms:
  - name: web-ubuntu
    box: "ubuntu/jammy64"
    memory: 2048
    interfaces:
      - network_name: forwarded_port
        guest: 80
        host: 8080

provisioner:
  name: ansible

verifier:
  name: ansible
