---
- name: Crear usuario redmine
  ansible.builtin.user:
    name: redmine 
    shell: /bin/bash 
    groups: users
    create_home: true
    state: present

- name: Agregar el usuario vagrant al grupo www-data
  ansible.builtin.user:
    name: vagrant
    groups: www-data
    append: yes

- name: Descargar Redmine
  get_url:
    url: '{{ redmine_url }}'
    dest: /tmp/redmine.tar.gz

- name: Extraer Redmine en /opt/redmine-6.0.6
  unarchive:
    src: /tmp/redmine.tar.gz
    dest: "/opt"
    remote_src: yes

- name: Cambiar propietario, grupo y permisos de /opt/redmine-6.0.6
  ansible.builtin.file:
    path: "{{ redmine_root_dir }}"
    owner: redmine
    group: www-data
    mode: '0777'
    recurse: yes

- name: Instalar paquetes básicos
  apt:
    name:
      - build-essential
      - curl
      - git
      - libmysqlclient-dev
    state: present
    update_cache: true

- name: Clonar asdf en el home de vagrant
  become: true
  become_user: vagrant
  git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: '/home/vagrant/.asdf'
    version: '{{ asdf_version }}'

- name: Configurar bashrc para asdf
  lineinfile:
    path: /home/vagrant/.bashrc
    line: '{{ item }}'
    create: yes
  loop:
    - '. "/home/vagrant/.asdf/asdf.sh"'
    - '. "/home/vagrant/.asdf/completions/asdf.bash"'
  become: true
  become_user: vagrant

- name: Instalar dependencias para Ruby y Redmine
  apt:
    name:
      - libssl-dev
      - libyaml-dev
      - libreadline6-dev
      - zlib1g-dev
      - libgmp-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm6
      - libgdbm-dev
      - libdb-dev
      - uuid-dev
    state: present

- name: Instalar plugin ruby en asdf y Ruby {{ ruby_version }}
  become: true
  become_user: "{{ redmine_user }}"
  shell: |
    echo $HOME
    export ASDF_DIR="$HOME/.asdf"
    . "$ASDF_DIR/asdf.sh"
    . "$ASDF_DIR/completions/asdf.bash"
    asdf plugin add ruby || true
    asdf install ruby {{ ruby_version }}
    asdf global ruby {{ ruby_version }}
    gem install bundler
  args:
    executable: /bin/bash

- name: Se configura database.yml en Redmine
  ansible.builtin.template:
    src: "database.yml.j2"
    dest: "{{ redmine_root_dir }}/config/database.yml"

- name: Se deshabilita la carga de contenido estatico desde Puma
  shell: |
    sed -i "s/^  # config.public_file_server.enabled/  config.public_file_server.enabled/" config/environments/production.rb
  args:
    chdir: "{{ redmine_root_dir }}"
    executable: /bin/bash

- name: Se aplica configuración de bundle al proyecto Redmine
  shell: |
    /home/vagrant/.asdf/shims/bundle config set --local without "development test"
  become: false
  args:
    chdir: "{{ redmine_root_dir }}"
    executable: /bin/bash

- name: Se agrega Gemfile.local
  ansible.builtin.copy:
    mode: "0777"
    dest: "{{ redmine_root_dir }}/Gemfile.local"
    owner: redmine
    group: www-data
    content: |
      gem 'puma'

- name: Instalar dependencias con Bundler
  shell: |
    echo $PATH
    bash -lc 'PATH=$PATH:/home/vagrant/.asdf/bin && /home/vagrant/.asdf/shims/bundle install'
  become: false
  args:
    chdir: "{{ redmine_root_dir }}"
    executable: /bin/bash

- name: Generar secret token
  shell: /home/vagrant/.asdf/shims/bundle exec rake generate_secret_token
  become: false
  args:
    chdir: "{{ redmine_root_dir }}"

- name: Ejecutar migraciones de base de datos
  shell: RAILS_ENV=production /home/vagrant/.asdf/shims/bundle exec rake db:migrate
  become: false
  args:
    chdir: "{{ redmine_root_dir }}"

- name: Cargar datos por defecto en español
  shell: |
    echo "es" | RAILS_ENV=production /home/vagrant/.asdf/shims/bundle exec rake redmine:load_default_data
  become: false
  args:
    chdir: "{{ redmine_root_dir }}"
    executable: /bin/bash

- name: Se configura redmine.service
  ansible.builtin.template:
    src: "redmine.service.j2"
    dest: "/etc/systemd/system/redmine.service"
  notify: Reload systemd

- name: Iniciar el servicio redmine.service
  ansible.builtin.systemd:
    name: redmine.service
    enabled: true
    state: started
  become: true

- name: Reiniar el servicio redmine.service
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: restarted
